# Generated by Django 5.0.6 on 2024-07-15 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='user',
            name='account_number',
            field=models.CharField(default='0000000000000000', max_length=16, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='credit_score',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
