# Generated by Django 5.0.6 on 2024-07-18 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_transactions'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='receiver',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
